--- #YAML:1.0
name:               MCE
version:            1.499_003
abstract:           Many-core Engine for Perl. Provides parallel processing capabilities.
author:
    - Mario E. Roy <marioeroy AT gmail DOT com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
    Test::More:           0.45
requires:
    Fcntl:         0
    File::Path:    0
    IPC::Open2:    0
    perl:          5.008
    Scalar::Util:  0
    Socket:        0
    Storable:      2.04
    Symbol:        0
    Time::HiRes:   0
resources:
    homepage:    http://code.google.com/p/many-core-engine-perl/
    license:     http://dev.perl.org/licenses/
    repository:  http://code.google.com/p/many-core-engine-perl/
no_index:
    directory:
        - t
        - inc
        - examples
        - images
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
