--- #YAML:1.0
name:               MCE
version:            1.201
abstract:           Many-Core Engine for Perl. Provides parallel processing capabilities.
author:
    - Mario E. Roy <marioeroy AT gmail DOT com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
    Test::More:           0.45
requires:
    Fcntl:       0
    File::Path:  0
    perl:        5.008
    Socket:      0
    Storable:    2.04
resources:
    homepage:    http://code.google.com/p/many-core-engine-perl/
    license:     http://dev.perl.org/licenses/
    repository:  http://code.google.com/p/many-core-engine-perl/
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
