--- #YAML:1.0
name:               MCE
version:            1.505
abstract:           Many-core Engine for Perl. Provides parallel processing capabilities.
author:
    - Mario E. Roy <marioeroy AT gmail DOT com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
    Test::More:           0.45
requires:
    Fcntl:         0
    File::Path:    0
    Getopt::Long:  0
    perl:          5.008
    Scalar::Util:  0
    Socket:        0
    Storable:      2.04
    Symbol:        0
    Time::HiRes:   0
resources:
    homepage:    http://code.google.com/p/many-core-engine-perl/
    license:     http://dev.perl.org/licenses/
    repository:  http://code.google.com/p/many-core-engine-perl/
provides:
    MCE:
        file:     lib/MCE.pm
        version:  1.505
    MCE::Core::Input::Generator:
        file:     lib/MCE/Core/Input/Generator.pm
        version:  1.505
    MCE::Core::Input::Handle:
        file:     lib/MCE/Core/Input/Handle.pm
        version:  1.505
    MCE::Core::Input::Iterator:
        file:     lib/MCE/Core/Input/Iterator.pm
        version:  1.505
    MCE::Core::Input::Request:
        file:     lib/MCE/Core/Input/Request.pm
        version:  1.505
    MCE::Core::Input::Sequence:
        file:     lib/MCE/Core/Input/Sequence.pm
        version:  1.505
    MCE::Core::Manager:
        file:     lib/MCE/Core/Manager.pm
        version:  1.505
    MCE::Core::Validation:
        file:     lib/MCE/Core/Validation.pm
        version:  1.505
    MCE::Core::Worker:
        file:     lib/MCE/Core/Worker.pm
        version:  1.505
    MCE::Flow:
        file:     lib/MCE/Flow.pm
        version:  1.505
    MCE::Grep:
        file:     lib/MCE/Grep.pm
        version:  1.505
    MCE::Loop:
        file:     lib/MCE/Loop.pm
        version:  1.505
    MCE::Map:
        file:     lib/MCE/Map.pm
        version:  1.505
    MCE::Queue:
        file:     lib/MCE/Queue.pm
        version:  1.505
    MCE::Signal:
        file:     lib/MCE/Signal.pm
        version:  1.505
    MCE::Stream:
        file:     lib/MCE/Stream.pm
        version:  1.505
    MCE::Subs:
        file:     lib/MCE/Subs.pm
        version:  1.505
    MCE::Util:
        file:     lib/MCE/Util.pm
        version:  1.505
no_index:
    directory:
        - t
        - inc
        - examples
        - images
    file:
        - bin/mce_grep
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
