--- #YAML:1.0
name:               MCE
version:            1.104
abstract:           Many-Core Engine for Perl. Provides parallel processing cabilities.
author:
    - Mario E. Roy <marioeroy AT gmail DOT com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Fcntl:       0
    File::Path:  0
    Socket:      0
    Storable:    2.04
    Test::More:  0.45
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
