Name:           perl-MCE
Version:        1.007
Release:        1%{?dist}
Summary:        Many-Core Engine for Perl. Provides parallel processing cabilities.
License:        CHECK(Distributable)
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/MCE/
Source0:        http://search.cpan.org/CPAN/authors/id/M/MA/MARIOROY/MCE-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
Many-core Engine (MCE) for Perl helps enable a new level of performance by
maximizing all available cores. One immediate benefit is that MCE does not
fork a new worker process per each element in an array. Instead, MCE
follows a bank queuing model. Imagine the line being the data and bank-
tellers the parallel workers. MCE enhances that model by adding the
ability to chunk the next n elements from the input stream to the next
available worker.

%prep
%setup -q -n MCE-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

for f in examples/*
do
    if [ ! -d $f ]
    then
        install -D -p -m 0755 $f $RPM_BUILD_ROOT%{_datadir}/doc/%{name}-%{version}/$f
    fi
done

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc CHANGES CREDITS README TODO examples
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Thu Nov 15 2012 Mario Roy 1.007-1
- At last, the "Voila" release :)
- Small change to __DIE__ and __WARN__ signal handling for spawn method
* Thu Nov 15 2012 Mario Roy 1.006-1
- Added description section to MCE::Signal's Perl doc
- Do not set trap on __DIE__ and __WARN__ inside MCE::Signal
- Localized __DIE__ and __WARN__ handlers inside MCE instead
- Clarify the use of threads in documentation
* Tue Nov 13 2012 Mario Roy 1.005-1
- Removed underscore from package globals in MCE::Signal
- Optimized _worker_read_handle method in MCE
- Updated files under examples/tbray/
* Mon Nov 12 2012 Mario Roy 1.004-1
- Updated examples/mce_usage.readme
- Updated examples/wide_finder.pl
- Added examples/tbray/README
- Added examples/tbray/tbray_baseline1.pl
- Added examples/tbray/tbray_baseline2.pl
- Added examples/tbray/wf_mce1.pl
- Added examples/tbray/wf_mce2.pl
- Added examples/tbray/wf_mce3.pl (../wide_finder.pl moved here)
- Added examples/tbray/wf_mmap.pl
* Sat Nov 10 2012 Mario Roy 1.003-1
- Updated README
- Updated images/06_Shared_Sockets.gif
- Updated images/10_Scaling_Pings.gif
- Added   images/11_SNMP_Collection.gif
- Small update to MCE::Signal
* Thu Nov 08 2012 Mario Roy 1.002-1
- Renamed continue method to next 
* Wed Nov 07 2012 Mario Roy 1.001-1
- Added perl-MCE.spec to trunk
  http://code.google.com/p/many-core-engine-perl/source/browse/trunk/
- Added CREDITS 
- Added 3 new methods to MCE.pm: continue, last, and exit
- Both foreach & forchunk now call run(1, {...}) to auto-shutdown workers
* Tue Nov 06 2012 Joe Ogulin 1.000-1
- Specfile autogenerated by cpanspec 1.77
- Modified to include the examples and install into /usr/share/doc
